In [ ]:
Input

In [50]:
import numpy as np

np.random.seed(2)

N = 77
ch = 256
H = 23
W = 41

h = np.random.randn(N, ch, H, W).astype(np.float32)
c = np.random.randint(low=0, high=10, size=(N,))

In [40]:
from cifar10_models import Cifar10Discriminator
import numpy as np
import torch

d = Cifar10Discriminator()

batchsize = 94

x_real = np.random.randn(batchsize, 3, 32, 32)
x_fake = np.random.randn(batchsize, 3, 32, 32)

x_real_t = torch.from_numpy(x_real).float()
x_fake_t = torch.from_numpy(x_fake).float()

eps = torch.rand(batchsize, 1, 1, 1)

x_mid = eps * x_real_t + (1 - eps) * x_fake_t
x_mid.detach()
x_mid.requires_grad = True

y_mid = d(x_mid)

device='cpu'
grad_outputs = torch.ones_like(y).to(device)

grads = torch.autograd.grad(
    outputs=y_mid, 
    inputs=x_mid,
    grad_outputs=grad_outputs,
    create_graph=True, retain_graph=True, only_inputs=True
)




In [44]:
grads[0]

tensor([[[[-2.7379e-04,  6.0373e-03, -8.1126e-03,  ..., -2.3483e-03,
           -6.2511e-04, -6.2645e-03],
          [-3.9958e-03, -1.9357e-03, -1.1247e-02,  ..., -1.0580e-02,
           -6.4290e-03, -4.9055e-03],
          [ 5.5178e-04, -3.8025e-03, -6.8274e-03,  ..., -4.1134e-03,
           -2.7571e-03, -5.3128e-03],
          ...,
          [ 8.0973e-04,  2.1361e-03, -4.8110e-03,  ..., -1.3275e-03,
           -4.0379e-03, -2.4637e-03],
          [ 3.9174e-03,  3.7620e-03, -4.1719e-03,  ..., -1.3490e-03,
           -6.3068e-03, -3.9776e-03],
          [-1.6741e-03, -1.9754e-03, -6.7247e-03,  ..., -3.2827e-03,
           -3.4770e-03, -4.7825e-03]],

         [[ 1.7558e-04,  5.1839e-03,  1.0983e-03,  ...,  2.0585e-03,
           -1.2118e-03, -3.0081e-03],
          [ 2.6435e-03, -1.3379e-03, -2.2619e-03,  ...,  4.3776e-03,
            4.4049e-03,  2.7772e-03],
          [ 7.1664e-03,  5.3255e-03,  3.1045e-03,  ...,  1.5984e-03,
            5.0585e-03,  6.4077e-03],
          ...,
     

In [14]:
sd = optim.state_dict()print(sd)

optim_2 = torch.optim.Adam(model.parameters(), lr = .001)
print(optim_2.state_dict())

optim_2.load_state_dict(sd)
print(optim_2.state_dict())



{'state': {}, 'param_groups': [{'lr': 1, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [4401396616, 4401393952]}]}
{'state': {}, 'param_groups': [{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [4401396616, 4401393952]}]}
{'state': {}, 'param_groups': [{'lr': 1, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [4401396616, 4401393952]}]}


In [167]:
import torchvision
import torchvision.transforms as transforms


trainset = torchvision.datasets.CIFAR10(
    root=DEFAULT_SN_GAN_DATA_PATH, 
    train=True,
    download=True, 
    # transform=transforms.ToTensor()
)

trainloader = torch.utils.data.DataLoader(
    trainset, 
    batch_size=64,
    num_workers=1,
    shuffle=True
)

Files already downloaded and verified


In [213]:
n = 100
image = trainset[n][0]

arr = torchvision.transforms.ToTensor()(image)

arr = arr*2 - 1
print(arr.shape)

img = torchvision.transforms.ToPILImage()(arr)

img.show()

torch.Size([3, 32, 32])


tensor([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],

In [34]:
class ConditionalBatchNorm2d(nn.Module):
    # Thanks to https://github.com/Kaixhin for this layer
    def __init__(self, num_features, num_classes):
        super().__init__()
        self.num_features = num_features
        self.bn = nn.BatchNorm2d(num_features, affine=False)
        self.embed = nn.Embedding(num_classes, num_features * 2)
        self.embed.weight.data[:, :num_features] = 1  
        self.embed.weight.data[:, num_features:] = 0  

    def forward(self, x, y):
        out = self.bn(x)
        gamma, beta = self.embed(y).chunk(2, 1)
        out = gamma.view(-1, self.num_features, 1, 1) * out + beta.view(-1, self.num_features, 1, 1)
        return out
    
ConditionalBatchNorm2d(128, 10).embed.weight.data

tensor([[1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        ...,
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.],
        [1., 1., 1.,  ..., 0., 0., 0.]])

In [3]:
from cifar10_models import Cifar10Discriminator
import torch 


dis = Cifar10Discriminator(n_classes=5)

im = torch.rand(94, 3, 32, 32) * 2 - 1
labels = torch.ones((94, ), dtype=torch.long)

dis(im, labels)

p shape:  torch.Size([94, 128])
label weight shape: torch.Size([94, 128])
label_weights * p shape: torch.Size([94, 128])
torch.Size([94, 1])


tensor([[-18.4368],
        [-17.7502],
        [-18.1937],
        [-18.2506],
        [-17.7299],
        [-17.4220],
        [-17.7976],
        [-17.4032],
        [-18.1591],
        [-17.5930],
        [-17.7073],
        [-17.3667],
        [-17.6906],
        [-18.0051],
        [-18.2365],
        [-17.4930],
        [-18.0018],
        [-17.9581],
        [-17.9253],
        [-17.1292],
        [-17.3356],
        [-17.7500],
        [-17.6907],
        [-18.5198],
        [-17.4648],
        [-17.8622],
        [-17.9219],
        [-18.0552],
        [-17.3677],
        [-18.0826],
        [-17.3437],
        [-17.3026],
        [-18.3996],
        [-17.8657],
        [-17.5924],
        [-17.0631],
        [-17.8615],
        [-17.8787],
        [-17.6510],
        [-17.2374],
        [-17.5856],
        [-18.1056],
        [-17.9741],
        [-17.7555],
        [-17.0572],
        [-17.3080],
        [-17.3251],
        [-17.7208],
        [-17.6329],
        [-17.8323],
