In [1]:
import numpy as np
import torch 

batch_size = 94
np.random.seed(0)

image_np = np.random.randn(batch_size, 3, 32, 32).astype(np.float32)
weight_np = np.random.randn(128, 3, 3, 3).astype(np.float32)
u_np = np.random.randn(1, 128).astype(np.float32)
h_np = np.random.randn(94, 128, 16, 16).astype(np.float32)
z_np = np.random.randn(94, 128).astype(np.float32)
h_gen_np = np.random.randn(94, 256, 4, 4).astype(np.float32)

image_chainer = image_np

print(np.sum(image_chainer))
print(np.sum(weight_np))
print(np.sum(u_np))
print(np.sum(h_np))
print(np.sum(h_gen_np))

image_torch = torch.from_numpy(image_np)
h_torch = torch.from_numpy(h_np)
h_gen_torch = torch.from_numpy(h_gen_np)
z_torch = torch.from_numpy(z_np)

464.95602
63.159615
5.7085176
-292.63834
991.6891


In [2]:
from cifar10_models import Cifar10Generator
from resnet_layers import GeneratorBlock

gen = Cifar10Generator()
torch.sum(gen(z_torch))

tensor(116731.1172, grad_fn=<SumBackward0>)

In [3]:
from cifar10_models import Cifar10Discriminator

dis = Cifar10Discriminator()
sum(torch.sum(parameter.data) for parameter in dis.parameters())

tensor(1052544.)

In [4]:
for parameter in dis.parameters():
    print(parameter)

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        ...,


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 

In [2]:
from spectral_layers import SNConv2d
import torch.nn as nn
import torch

lin = SNConv2d(3, 256, 3, padding=1)
lin.weight.data = torch.from_numpy(weight_np)
lin.bias[:] = 0
lin.u = torch.from_numpy(u_np)


lin(image_torch)
lin(image_torch)

tensor([[[[ 1.5623e-01,  1.7736e-01, -6.2803e-02,  ..., -5.0368e-01,
           -8.4833e-02, -3.4215e-01],
          [-4.1501e-02,  1.9460e-01, -9.9612e-02,  ...,  6.8749e-01,
            7.3563e-01,  3.3125e-01],
          [-3.3088e-02,  5.9294e-02,  1.2186e-01,  ..., -5.7081e-01,
           -4.5163e-01, -3.4642e-01],
          ...,
          [-4.7068e-01, -2.2244e-02, -4.0426e-01,  ..., -1.0163e-01,
           -1.4517e-01, -9.9677e-02],
          [ 2.4484e-01, -1.4914e-01, -1.1124e-01,  ...,  3.3552e-02,
           -1.7560e-01,  2.0205e-01],
          [-1.3018e-01, -3.2673e-02, -3.9648e-01,  ...,  2.0517e-01,
           -1.5648e-01,  3.1624e-02]],

         [[ 2.0480e-02, -1.2350e-01, -7.1649e-02,  ...,  2.2243e-01,
            9.2680e-02,  8.4569e-03],
          [ 3.2644e-01,  3.5563e-01, -8.4679e-02,  ...,  4.6662e-01,
           -6.3487e-02, -2.4449e-01],
          [-3.4767e-02, -2.5741e-01, -5.7003e-01,  ..., -1.4075e-01,
           -2.9494e-01, -2.4837e-01],
          ...,
     

In [12]:
var = torch.zeros(1, 5)

var[:] = 1
var

tensor([[1., 1., 1., 1., 1.]])

In [8]:
from cifar10_models import Cifar10Discriminator

torch_dis = Cifar10Discriminator()
torch_dis.block1(image_torch)

tensor([[[[ 4.2778e-02,  9.5806e-02,  1.4641e-02,  ..., -5.7526e-02,
            1.0365e-01,  2.0031e-01],
          [-3.1524e-01,  2.4977e-01,  1.7364e-01,  ...,  1.7202e-01,
           -4.4028e-02,  9.1172e-02],
          [ 1.2984e-01,  2.5971e-01, -3.3592e-01,  ...,  1.6341e-01,
           -1.7969e-01,  1.8892e-02],
          ...,
          [ 1.1952e-02, -5.9973e-02,  3.7246e-02,  ...,  1.0876e-01,
           -8.9766e-02,  1.7587e-01],
          [ 1.5132e-01, -9.1140e-02,  1.8220e-01,  ...,  1.3009e-01,
            3.7137e-02,  2.6910e-01],
          [ 3.3333e-01,  1.5035e-01,  2.5332e-01,  ...,  2.9391e-01,
            1.6580e-01,  1.3591e-01]],

         [[ 3.3454e-01,  4.5871e-01,  5.2936e-01,  ...,  2.7687e-01,
            3.5778e-01,  3.1035e-01],
          [ 3.4950e-02,  3.6140e-01,  3.2614e-01,  ...,  3.0568e-01,
            3.7203e-01,  3.5937e-01],
          [ 5.6948e-01,  1.4173e-01,  7.7703e-02,  ...,  2.0236e-01,
            4.9393e-01,  1.8872e-01],
          ...,
     